name: 'Lyn-Art '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9095383435487747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9673223930876702
  lightness: 0.9518235689029098
  saturation: 0.44989756192080677
  rhythmicContrast: 0.7810239039827138
purpose:
  - type: contact
    url: 'tel:6128044869'
    label: 'Phone: 6128044869'
  - type: contact
    url: 'mailto:lynwiegand@gmail.com'
    label: 'Email me:'
content: []
title: Lyn Wiegand Illustration
description: 'Illustration, Graphics, Textile Design & More'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1ac775db-dfb1-4986-a2c7-7ca52db2c8ac.jpg
content_rating:
  adult: false
